### ISSUE TITLE
datatime now changes between 3.10 and 3.12

### ISSUE THREAD

**Issue by pvgenuchten** [geopython/pygeometa#302]
in a python 3.10, this test fails (but works in 3.12)

```
  pygeometa/core.py", line 128, in normalize_datestring
    today_and_now = datetime.datetime.now(datetime.UTC)
AttributeError: module 'datetime' has no attribute 'UTC'
```
datetime.UTC was added in 3.11

use instead

```
import datetime

today_and_now = datetime.datetime.now(datetime.timezone.utc)
```
